language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.6

env:
  global:
    # test invocation
    - TESTFOLDER="tests"

before_install:
# Here we download miniconda and install the dependencies
- pip install black coverage future joblib numpy numpydoc pandas patsy progressbar2 pygam pytest python-dateutil python-utils pytz scikit-learn scipy six statsmodels xgboost

install:
- python setup.py install

script:
- coverage run -m pytest $TESTFOLDER

after_success:
- bash <(curl -s https://codecov.io/bash)
